environment:
  matrix:
    - nodejs_version: 10
    - nodejs_version: 8
    - nodejs_version: 6

install:
  - git rev-parse HEAD
  - ps: Install-Product node $env:nodejs_version
  - npm version
  - npm install

cache:
  - '%APPDATA%\npm-cache'

build: off

test_script:
  - npm test
