engines:
  duplication:
    enabled: true
  fixme:
    enabled: true
  nodesecurity:
    enabled: true

ratings:
  paths:
    - lib/**
    - test/**

exclude_paths:
  - example/**/*
  - node_modules/**/*
